package com.sqlorb;

import java.util.List;

/**
 * The Master Parser (The Router).
 * <p>
 * This class is the main entry point for the parsing engine.
 * It initializes the shared ParserContext and routes the parsing 
 * responsibility to specific sub-parsers (DDL, DML, DQL, Control) 
 * based on the first token of the statement.
 */
public class SQLParser {
    private final ParserContext ctx;
    
    // Sub-Parsers
    private final DDLParser ddlParser;
    private final DMLParser dmlParser;
    private final DQLParser dqlParser;
    private final ControlParser controlParser;

    /**
     * Initializes the parser with a list of tokens.
     * @param tokens The list of tokens generated by the Lexer.
     */
    public SQLParser(List<Token> tokens) {
        // 1. Create the shared context (The State)
        this.ctx = new ParserContext(tokens);

        // 2. Initialize sub-parsers with the same context
        this.ddlParser = new DDLParser(ctx);
        this.dmlParser = new DMLParser(ctx);
        this.dqlParser = new DQLParser(ctx);
        this.controlParser = new ControlParser(ctx);
    }

    /**
     * Executes the parsing logic.
     * Routes the query to the correct sub-parser.
     */
    public void parse() {
        // Look at the first token to decide who handles this query
        Token startToken = ctx.peek();

        if (startToken.type == TokenType.EOF) {
            return; // Empty query
        }

        switch (startToken.type) {
            // --- DDL (Structure) ---
            case CREATE:
            case DROP:
            case ALTER:
            case TRUNCATE:
                ddlParser.parse();
                break;

            // --- DQL (Query) ---
            case SELECT:
                dqlParser.parseQuery();
                break;

            // --- DML (Data Modification) ---
            case INSERT:
            case UPDATE:
            case DELETE:
                dmlParser.parse(); // This requires DMLParser.java to have the parse() method!
                break;

            // --- TCL & DCL (Control) ---
            case GRANT:
            case REVOKE:
            case COMMIT:
            case ROLLBACK:
            case SAVEPOINT:
                controlParser.parse();
                break;

            default:
                throw new RuntimeException("Syntax Error: Unexpected start of query: " + startToken.value);
        }

        // Ensure we reached the end of the query (or a semicolon)
        if (ctx.peek().type == TokenType.SEMICOLON) {
            ctx.advance();
        } else if (ctx.peek().type != TokenType.EOF) {
             throw new RuntimeException("Syntax Error: Text found after end of statement: " + ctx.peek().value);
        }
    }
}